version: "3.7"

networks:
  sister2:
    name: sister2

services:

  main:
    # to test this jwilder/LE
    # http://web-108-168-7-24.nip.io/
    # https://web.198.144.183.160.nip.io/
    image: nginx:1.21-alpine
    volumes:
      - ./site:/usr/share/nginx/html
    expose:
      - "80"
    # environment:
      # - VIRTUAL_HOST=davegg.com,198.144.183.160.nip.io,d.davegg.com
      # - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=davegg.com,198.144.183.160.nip.io,d.davegg.com
      #- LETSENCRYPT_HOST=web.c617eef4.nip.io
      # - LETSENCRYPT_EMAIL=dgleba@gmail.com
    restart: always
    networks:
      - sister2
