---
# Shaarli - Docker Compose example configuration
#
# See:
# - https://shaarli.readthedocs.io/en/master/Docker/#docker-compose
#
# Environment variables:
# - SHAARLI_VIRTUAL_HOST      Fully Qualified Domain Name for the Shaarli instance
# - SHAARLI_LETSENCRYPT_EMAIL Contact email for certificate renewal
# - SHAARLI_DOCKER_TAG        Shaarli docker tag to use
#                             See: https://hub.docker.com/r/shaarli/shaarli/tags
version: '3'

# networks:
  # http-proxy:
  # sister:
    # # name: sister


volumes:
  # traefik-acme:
  shaarli-cache:
  shaarli-data:

services:

  shaarli:
    # http://192.168.88.60:14811
    # http://172.27.0.30:14811
    # https://shar.dg.jgleba.com  
    image: shaarli/shaarli:${SHAARLI_DOCKER_TAG}
    # build: ./
    # networks:
      # - http-proxy
      # - sister
    volumes:
      # - ../sysdata/sharlicache601c:/var/www/shaarli/cache
      # - ../data_sharli_601c:/var/www/shaarli/data
      # above not working. It must be this??
      - shaarli-cache:/var/www/shaarli/cache
      - shaarli-data:/var/www/shaarli/data
    ports:
      - 14811:80
      # - 443:443
    # environment:
      # - SHAARLI_VIRTUAL_HOST=shar.d.jgleba.com  
      # - VIRTUAL_NETWORK=sister
      # - VIRTUAL_PORT=80
      # - VIRTUAL_HOST=shar.d.jgleba.com
      # - LETSENCRYPT_HOST=shar.d.jgleba.com
      # - LETSENCRYPT_EMAIL=dgleba@gmail.com


    # labels:
    #   traefik.domain: "${SHAARLI_VIRTUAL_HOST}"
    #   traefik.backend: shaarli
    #   traefik.frontend.rule: "Host:${SHAARLI_VIRTUAL_HOST}"

    # traefik:
    #   image: traefik:1.7-alpine
    #   command:
    #     - "--defaultentrypoints=http,https"
    #     - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
    #     - "--entrypoints=Name:https Address::443 TLS"
    #     - "--retry"
    #     - "--docker"
    #     - "--docker.domain=${SHAARLI_VIRTUAL_HOST}"
    #     - "--docker.exposedbydefault=true"
    #     - "--docker.watch=true"
    #     - "--acme"
    #     - "--acme.domains=${SHAARLI_VIRTUAL_HOST}"
    #     - "--acme.email=${SHAARLI_LETSENCRYPT_EMAIL}"
    #     - "--acme.entrypoint=https"
    #     - "--acme.onhostrule=true"
    #     - "--acme.storage=/acme/acme.json"
    #     - "--acme.httpchallenge"
    #     - "--acme.httpchallenge.entrypoint=http"
    #   networks:
    #     - http-proxy
    #   ports:
    #     - 80:80
    #     - 443:443
    #   volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock:ro
    #     - traefik-acme:/acme
